title: PyMCON 2020
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "" # the subpath of your site, e.g. /blog
project_name: pymcon
url: "https://pymc-devs.github.io/pymcon/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

logo: "./css/2016_style/img/icon-large.png"

social:
  name: Your Facebook Page
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pymc_devs

# Build settings
markdown: kramdown
permalink: pretty
