title: "PyMCON 2020"
description: > # this means to ignore newlines until "baseurl:"
  An asynchronous-first virtual conference for the Bayesian community.


url: "https://pymc-devs.github.io/pymcon" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
project_name: pymcon
# Build settings
markdown: kramdown

logo: "../css/2017_style/img/logos/pymcon_logo.png"

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/pymc_devs
  - title: github
    url: https://github.com/pymc-devs
  - title: heart
    url: https://numfocus.org/donate-to-pymc3

# Build settings
markdown: kramdown
permalink: pretty

page_gen-dirs: false

page_gen:
- data: 'speakers'
  template: 'speaker'
  dir: ''
  name: 'name'

# Front Matter Defaults
# see https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  # _posts
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "/css/2017_style/img/logos/pymcon_logo.png"
